<?php

return [
    'version' => '202610030001',
    'description' => 'Add canonical project file metadata, folders, operations, and audit events',
    'statements' => [
        "CREATE TABLE IF NOT EXISTS project_file_folders (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            public_id CHAR(36) NOT NULL,
            project_id BIGINT UNSIGNED NOT NULL,
            parent_folder_id BIGINT UNSIGNED NULL,
            name VARCHAR(255) NOT NULL,
            normalized_name VARCHAR(255) NOT NULL,
            root_marker TINYINT UNSIGNED NULL,
            created_by_participant_id BIGINT UNSIGNED NOT NULL,
            version BIGINT UNSIGNED NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            deleted_at DATETIME NULL,
            PRIMARY KEY (id),
            UNIQUE KEY uq_project_file_folders_public_id (public_id),
            UNIQUE KEY uq_project_file_folders_root (project_id, root_marker),
            KEY idx_project_file_folders_parent (project_id, parent_folder_id, deleted_at, normalized_name(160), id),
            CONSTRAINT fk_project_file_folders_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
            CONSTRAINT fk_project_file_folders_parent FOREIGN KEY (parent_folder_id) REFERENCES project_file_folders(id),
            CONSTRAINT fk_project_file_folders_creator FOREIGN KEY (created_by_participant_id) REFERENCES project_participants(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_files (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            public_id CHAR(36) NOT NULL,
            project_id BIGINT UNSIGNED NOT NULL,
            folder_id BIGINT UNSIGNED NOT NULL,
            storage_driver VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
            storage_key VARCHAR(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
            original_name VARCHAR(255) NOT NULL,
            display_name VARCHAR(255) NOT NULL,
            normalized_name VARCHAR(255) NOT NULL,
            mime_type VARCHAR(191) NOT NULL,
            size_bytes BIGINT UNSIGNED NOT NULL,
            sha256 CHAR(64) NOT NULL,
            uploaded_by_participant_id BIGINT UNSIGNED NOT NULL,
            state ENUM('pending','available','unavailable','deleted','integrity_failed') NOT NULL DEFAULT 'pending',
            version BIGINT UNSIGNED NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            deleted_at DATETIME NULL,
            PRIMARY KEY (id),
            UNIQUE KEY uq_project_files_public_id (public_id),
            UNIQUE KEY uq_project_files_storage_object (storage_driver, storage_key),
            KEY idx_project_files_folder (project_id, folder_id, state, normalized_name(160), id),
            KEY idx_project_files_created (project_id, state, created_at, id),
            KEY idx_project_files_integrity (storage_driver, state, updated_at, id),
            CONSTRAINT fk_project_files_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
            CONSTRAINT fk_project_files_folder FOREIGN KEY (folder_id) REFERENCES project_file_folders(id),
            CONSTRAINT fk_project_files_uploader FOREIGN KEY (uploaded_by_participant_id) REFERENCES project_participants(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_file_operations (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            project_id BIGINT UNSIGNED NOT NULL,
            actor_participant_id BIGINT UNSIGNED NOT NULL,
            idempotency_key VARCHAR(160) NOT NULL,
            request_fingerprint CHAR(64) NOT NULL,
            action VARCHAR(60) NOT NULL,
            file_id BIGINT UNSIGNED NULL,
            folder_id BIGINT UNSIGNED NULL,
            response_json MEDIUMTEXT NOT NULL,
            created_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            UNIQUE KEY uq_project_file_operations_retry (project_id, actor_participant_id, idempotency_key),
            KEY idx_project_file_operations_created (project_id, created_at, id),
            CONSTRAINT fk_project_file_operations_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
            CONSTRAINT fk_project_file_operations_actor FOREIGN KEY (actor_participant_id) REFERENCES project_participants(id),
            CONSTRAINT fk_project_file_operations_file FOREIGN KEY (file_id) REFERENCES project_files(id),
            CONSTRAINT fk_project_file_operations_folder FOREIGN KEY (folder_id) REFERENCES project_file_folders(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_file_events (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            public_id CHAR(36) NOT NULL,
            project_id BIGINT UNSIGNED NOT NULL,
            actor_participant_id BIGINT UNSIGNED NOT NULL,
            file_id BIGINT UNSIGNED NULL,
            folder_id BIGINT UNSIGNED NULL,
            action VARCHAR(60) NOT NULL,
            metadata_json MEDIUMTEXT NULL,
            created_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            UNIQUE KEY uq_project_file_events_public_id (public_id),
            KEY idx_project_file_events_project (project_id, created_at, id),
            KEY idx_project_file_events_file (project_id, file_id, created_at, id),
            CONSTRAINT fk_project_file_events_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
            CONSTRAINT fk_project_file_events_actor FOREIGN KEY (actor_participant_id) REFERENCES project_participants(id),
            CONSTRAINT fk_project_file_events_file FOREIGN KEY (file_id) REFERENCES project_files(id),
            CONSTRAINT fk_project_file_events_folder FOREIGN KEY (folder_id) REFERENCES project_file_folders(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ],
];

