<?php

return [
    'version' => '202609250004',
    'description' => 'Expand the protected built-in project template catalog',
    'statements' => [
        "INSERT INTO project_templates
            (public_id, category_id, name, description, instructions, origin, status, version, created_by_user_id, updated_by_user_id, created_at, updated_at)
         VALUES
            ('00000000-0000-4000-8000-000000000201', (SELECT id FROM project_template_categories WHERE slug = 'general'), 'Cross-Functional Initiative',
             'Coordinate a bounded initiative that requires contributions from multiple disciplines or teams.',
             'Define the outcome, decision authority, workstreams, dependencies, and acceptance criteria before execution. Keep ownership explicit, coordinate handoffs through shared evidence, surface conflicting priorities early, and require independent confirmation that the integrated result satisfies the agreed outcome.',
             'system', 'active', 1, NULL, NULL, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ('00000000-0000-4000-8000-000000000202', (SELECT id FROM project_template_categories WHERE slug = 'software-development'), 'Security Review and Hardening',
             'Assess a software surface for concrete security risks, implement approved hardening, and verify the resulting controls.',
             'Establish assets, trust boundaries, threat assumptions, and authorization constraints before testing. Use reproducible evidence, prioritize findings by realistic impact and likelihood, avoid destructive testing without approval, keep remediation scoped, and independently verify that controls address the demonstrated risk without weakening required behavior.',
             'system', 'active', 1, NULL, NULL, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ('00000000-0000-4000-8000-000000000203', (SELECT id FROM project_template_categories WHERE slug = 'operations'), 'Incident Response and Recovery',
             'Contain an operational incident, determine its cause and impact, restore safe service, and preserve follow-up evidence.',
             'Establish incident authority, severity, scope, communication cadence, and evidence-preservation requirements immediately. Separate containment from permanent correction, record material actions and timestamps, require explicit approval for destructive recovery steps, verify restored service and security boundaries, and track corrective actions through closure.',
             'system', 'active', 1, NULL, NULL, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ('00000000-0000-4000-8000-000000000204', (SELECT id FROM project_template_categories WHERE slug = 'operations'), 'Deployment and Release',
             'Prepare, execute, verify, and close a controlled application or infrastructure release.',
             'Define the exact release identity, scope, environment, prerequisites, rollback conditions, and approval gates before deployment. Preserve provenance and checksums, separate preparation from execution, record operator actions, stop on failed gates or uncertain outcomes, verify critical behavior after release, and retain a clear rollback and follow-up record.',
             'system', 'active', 1, NULL, NULL, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ('00000000-0000-4000-8000-000000000205', (SELECT id FROM project_template_categories WHERE slug = 'research-decision'), 'Architecture Decision Record',
             'Evaluate a material technical decision and preserve the selected option, rationale, constraints, and consequences.',
             'State the decision, scope, constraints, quality attributes, and evaluation criteria before comparing options. Include the current approach and credible alternatives, distinguish evidence from preference, expose reversibility and migration costs, require critical review, and record the approved decision with consequences and conditions for reconsideration.',
             'system', 'active', 1, NULL, NULL, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ('00000000-0000-4000-8000-000000000206', (SELECT id FROM project_template_categories WHERE slug = 'business-commercial'), 'Commercial Readiness Review',
             'Assess whether a product or release is ready for a defined commercial audience, commitment, or launch stage.',
             'Define the target customer, offer, evidence threshold, commercial claims, dependencies, and decision gate. Review product capability, delivery readiness, supportability, security and compliance constraints, pricing or packaging assumptions, and unresolved risks. Separate verified readiness from planned work and end with a clear recommendation, conditions, and owner decisions.',
             'system', 'active', 1, NULL, NULL, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ('00000000-0000-4000-8000-000000000207', (SELECT id FROM project_template_categories WHERE slug = 'documentation-content'), 'Technical Documentation',
             'Produce accurate, usable technical documentation from verified product behavior and subject-matter evidence.',
             'Define the audience, purpose, supported versions, document structure, source evidence, and acceptance criteria before drafting. Verify procedures against the actual product where practical, distinguish required steps from optional guidance, avoid unsupported claims, preserve terminology consistency, and require technical and reader-focused review before publication.',
             'system', 'active', 1, NULL, NULL, UTC_TIMESTAMP(), UTC_TIMESTAMP())
         ON DUPLICATE KEY UPDATE category_id = VALUES(category_id), name = VALUES(name), description = VALUES(description), instructions = VALUES(instructions), origin = 'system', status = 'active', updated_at = VALUES(updated_at)",
        "INSERT INTO project_template_agents
            (template_id, preset_key, display_name, provider, role_title, role_summary, role_instructions, supervising_agent_id, sort_order, created_at, updated_at)
         VALUES
            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000201'), 'initiative-coordinator', 'Initiative Coordinator', 'unassigned', 'Initiative Coordinator',
             'Coordinates scope, owners, dependencies, decisions, and integrated delivery across workstreams.',
             'Maintain the shared outcome, workstream boundaries, dependency map, decision log, and completion evidence. Resolve routine coordination issues and escalate conflicting priorities or authority questions to the project owner.', NULL, 10, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000201'), 'delivery-specialist', 'Delivery Specialist', 'unassigned', 'Delivery Specialist',
             'Owns a defined workstream and produces its complete, verifiable contribution.',
             'Confirm the assigned workstream and interfaces, execute within scope, preserve compatibility with adjacent work, communicate dependency changes early, and provide evidence suitable for integration review.', NULL, 20, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000201'), 'integration-reviewer', 'Integration Reviewer', 'unassigned', 'Integration Reviewer',
             'Independently checks whether workstream outputs combine into the agreed overall result.',
             'Review cross-workstream assumptions, handoffs, gaps, and acceptance evidence. Test the integrated outcome where practical and report unresolved conflicts or missing ownership without taking over delivery.', NULL, 30, UTC_TIMESTAMP(), UTC_TIMESTAMP()),

            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000202'), 'security-analyst', 'Security Analyst', 'unassigned', 'Security Analyst',
             'Maps trust boundaries, tests prioritized threats, and records reproducible security findings.',
             'Work within approved testing boundaries, protect sensitive evidence, demonstrate realistic exploit paths or control gaps, distinguish confirmed findings from hypotheses, and recommend proportionate remediation.', NULL, 10, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000202'), 'remediation-engineer', 'Remediation Engineer', 'unassigned', 'Remediation Engineer',
             'Implements approved security corrections while preserving required system behavior.',
             'Trace each correction to a confirmed finding, keep the change focused, preserve authorization and compatibility, add regression coverage, and document residual risk or operational tradeoffs.', NULL, 20, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000202'), 'security-verifier', 'Security Verifier', 'unassigned', 'Security Verification Reviewer',
             'Independently verifies remediations and checks for regressions or unsupported closure claims.',
             'Reproduce the original evidence where safe, verify the corrected control and adjacent boundaries, review regression coverage, and state clearly which risks are closed, reduced, accepted, or still unknown.', NULL, 30, UTC_TIMESTAMP(), UTC_TIMESTAMP()),

            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000203'), 'incident-coordinator', 'Incident Coordinator', 'unassigned', 'Incident Coordinator',
             'Maintains incident authority, priorities, communication, decisions, and the recovery gate.',
             'Set severity and cadence, assign investigation and recovery ownership, maintain the event record, protect against conflicting actions, and escalate destructive or high-impact decisions to the authorized owner.', NULL, 10, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000203'), 'incident-investigator', 'Incident Investigator', 'unassigned', 'Incident Investigator',
             'Determines scope, impact, timeline, and likely cause while preserving operational evidence.',
             'Collect bounded evidence, test hypotheses, distinguish observed facts from inference, identify affected systems and data, and provide actionable findings without disrupting containment or recovery.', NULL, 20, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000203'), 'recovery-verifier', 'Recovery Verifier', 'unassigned', 'Recovery and Controls Verifier',
             'Validates restored service, security controls, data integrity, and readiness to close the incident.',
             'Verify recovery criteria independently, test critical and adjacent workflows, confirm containment remains effective, identify residual risks, and require explicit evidence before recommending closure.', NULL, 30, UTC_TIMESTAMP(), UTC_TIMESTAMP()),

            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000204'), 'release-coordinator', 'Release Coordinator', 'unassigned', 'Release Coordinator',
             'Owns release identity, gates, sequencing, communication, and go or no-go coordination.',
             'Confirm provenance, scope, prerequisites, approvals, rollback criteria, and operator assignments. Keep the release record current and stop the workflow when a gate fails or mutation outcome is uncertain.', NULL, 10, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000204'), 'deployment-operator', 'Deployment Operator', 'unassigned', 'Deployment Operator',
             'Executes the approved release plan against the authorized target environment.',
             'Follow the exact runbook, verify each prerequisite, record material actions and outputs, protect credentials, avoid unapproved improvisation, and stop and escalate on unexpected state or uncertain mutations.', NULL, 20, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000204'), 'release-verifier', 'Release Verifier', 'unassigned', 'Release Verification Reviewer',
             'Independently confirms package identity, deployment health, critical behavior, and rollback readiness.',
             'Verify the deployed identity and checksums, execute the approved smoke and risk tests, inspect health signals, and report objective pass, rollback, or follow-up recommendations.', NULL, 30, UTC_TIMESTAMP(), UTC_TIMESTAMP()),

            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000205'), 'solution-architect', 'Solution Architect', 'unassigned', 'Solution Architect',
             'Frames the decision and develops viable architecture options against explicit constraints.',
             'Document the current context, required qualities, constraints, options, evidence, transition implications, and a reasoned recommendation without hiding uncertainty or material tradeoffs.', NULL, 10, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000205'), 'architecture-reviewer', 'Architecture Reviewer', 'unassigned', 'Architecture Reviewer',
             'Challenges option completeness, assumptions, operational consequences, and evidence quality.',
             'Review alternatives independently, test claims against constraints and likely failure modes, identify missing stakeholders or reversibility costs, and provide specific corrective feedback.', NULL, 20, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000205'), 'decision-recorder', 'Decision Recorder', 'unassigned', 'Decision Recorder',
             'Preserves the approved decision, rationale, consequences, ownership, and reconsideration conditions.',
             'Synthesize the reviewed record faithfully, separate the final decision from rejected options, capture consequences and follow-up work, and maintain a concise durable artifact suitable for future readers.', NULL, 30, UTC_TIMESTAMP(), UTC_TIMESTAMP()),

            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000206'), 'commercial-assessor', 'Commercial Assessor', 'unassigned', 'Commercial Assessor',
             'Evaluates the offer, audience, claims, packaging, dependencies, and commercial decision gate.',
             'Define the readiness standard, test commercial assumptions against available evidence, distinguish current capability from roadmap intent, identify owner decisions, and provide a clear readiness recommendation.', NULL, 10, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000206'), 'product-readiness-analyst', 'Product Readiness Analyst', 'unassigned', 'Product Readiness Analyst',
             'Assesses product capability, delivery evidence, supportability, and customer-facing gaps.',
             'Map the intended offer to verified product behavior, operational support, onboarding, documentation, and service dependencies. Record concrete evidence and gaps without overstating readiness.', NULL, 20, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000206'), 'commercial-risk-reviewer', 'Commercial Risk Reviewer', 'unassigned', 'Commercial Risk Reviewer',
             'Independently reviews commercial, operational, security, compliance, and commitment risks.',
             'Challenge readiness claims, identify unsupported commitments and residual dependencies, assess whether mitigations are credible, and state which risks require owner acceptance or block advancement.', NULL, 30, UTC_TIMESTAMP(), UTC_TIMESTAMP()),

            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000207'), 'technical-writer', 'Technical Writer', 'unassigned', 'Technical Writer',
             'Turns verified product behavior and source evidence into clear audience-appropriate documentation.',
             'Follow the agreed structure and terminology, write actionable procedures and explanations, identify missing evidence instead of guessing, and keep version and prerequisite boundaries explicit.', NULL, 10, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000207'), 'subject-matter-reviewer', 'Subject Matter Reviewer', 'unassigned', 'Subject Matter Reviewer',
             'Checks technical accuracy, completeness, supported behavior, and version applicability.',
             'Review the document against authoritative implementation or operating evidence, reproduce procedures where practical, correct unsupported statements, and identify required caveats or prerequisites.', NULL, 20, UTC_TIMESTAMP(), UTC_TIMESTAMP()),
            ((SELECT id FROM project_templates WHERE public_id = '00000000-0000-4000-8000-000000000207'), 'documentation-qa', 'Documentation QA', 'unassigned', 'Documentation Quality Reviewer',
             'Validates readability, navigation, consistency, accessibility, and task completion for the target audience.',
             'Review from the reader perspective, test whether required tasks can be completed, identify ambiguity and terminology drift, verify links and examples, and provide focused publication-blocking findings.', NULL, 30, UTC_TIMESTAMP(), UTC_TIMESTAMP())
         ON DUPLICATE KEY UPDATE display_name = VALUES(display_name), provider = VALUES(provider), role_title = VALUES(role_title), role_summary = VALUES(role_summary), role_instructions = VALUES(role_instructions), sort_order = VALUES(sort_order), updated_at = VALUES(updated_at)",
    ],
];
