<?php

return [
    'version' => '202609050002_collaboration_core',
    'description' => 'Add sessions, invitations, canonical messages, settings, audits, and integration outbox',
    'statements' => [
        "CREATE TABLE IF NOT EXISTS syndicatum_sessions (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            user_id BIGINT UNSIGNED NOT NULL,
            token_hash CHAR(64) NOT NULL UNIQUE,
            csrf_token_hash CHAR(64) NOT NULL,
            account_session_id VARCHAR(160) NULL,
            ip_address VARCHAR(80) NULL,
            user_agent VARCHAR(255) NULL,
            created_at DATETIME NOT NULL,
            last_seen_at DATETIME NOT NULL,
            expires_at DATETIME NOT NULL,
            revoked_at DATETIME NULL,
            INDEX idx_syndicatum_sessions_user (user_id, revoked_at, expires_at),
            CONSTRAINT fk_syndicatum_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_invitations (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            project_id BIGINT UNSIGNED NOT NULL,
            invited_email VARCHAR(191) NOT NULL,
            role ENUM('admin', 'member', 'viewer') NOT NULL DEFAULT 'member',
            token_hash CHAR(64) NOT NULL UNIQUE,
            invited_by_user_id BIGINT UNSIGNED NOT NULL,
            accepted_by_user_id BIGINT UNSIGNED NULL,
            status ENUM('pending', 'accepted', 'rejected', 'expired', 'revoked') NOT NULL DEFAULT 'pending',
            expires_at DATETIME NOT NULL,
            created_at DATETIME NOT NULL,
            responded_at DATETIME NULL,
            INDEX idx_project_invitations_lookup (project_id, invited_email, status),
            CONSTRAINT fk_project_invitations_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
            CONSTRAINT fk_project_invitations_inviter FOREIGN KEY (invited_by_user_id) REFERENCES users(id),
            CONSTRAINT fk_project_invitations_acceptor FOREIGN KEY (accepted_by_user_id) REFERENCES users(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_message_sequences (
            project_id BIGINT UNSIGNED PRIMARY KEY,
            next_sequence BIGINT UNSIGNED NOT NULL DEFAULT 1,
            CONSTRAINT fk_project_message_sequences_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS messages (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            message_uuid CHAR(36) NOT NULL UNIQUE,
            legacy_entry_id BIGINT UNSIGNED NULL UNIQUE,
            project_id BIGINT UNSIGNED NOT NULL,
            project_sequence BIGINT UNSIGNED NOT NULL,
            sender_participant_id BIGINT UNSIGNED NOT NULL,
            reply_to_message_id BIGINT UNSIGNED NULL,
            body MEDIUMTEXT NOT NULL,
            client_idempotency_key VARCHAR(160) NULL,
            correlation_id VARCHAR(160) NULL,
            reply_depth SMALLINT UNSIGNED NOT NULL DEFAULT 0,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            deleted_at DATETIME NULL,
            UNIQUE KEY uq_messages_project_sequence (project_id, project_sequence),
            UNIQUE KEY uq_messages_idempotency (project_id, sender_participant_id, client_idempotency_key),
            INDEX idx_messages_project_page (project_id, deleted_at, project_sequence),
            INDEX idx_messages_sender (sender_participant_id, project_sequence),
            CONSTRAINT fk_messages_legacy FOREIGN KEY (legacy_entry_id) REFERENCES chat_entries(id),
            CONSTRAINT fk_messages_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
            CONSTRAINT fk_messages_sender FOREIGN KEY (sender_participant_id) REFERENCES project_participants(id),
            CONSTRAINT fk_messages_reply FOREIGN KEY (reply_to_message_id) REFERENCES messages(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS message_addressees (
            message_id BIGINT UNSIGNED NOT NULL,
            participant_id BIGINT UNSIGNED NOT NULL,
            reason ENUM('direct', 'mention', 'broadcast') NOT NULL,
            notified_at DATETIME NULL,
            seen_at DATETIME NULL,
            acknowledged_at DATETIME NULL,
            created_at DATETIME NOT NULL,
            PRIMARY KEY (message_id, participant_id),
            INDEX idx_message_addressees_responsibility (participant_id, acknowledged_at, message_id),
            CONSTRAINT fk_message_addressees_message FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE,
            CONSTRAINT fk_message_addressees_participant FOREIGN KEY (participant_id) REFERENCES project_participants(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS message_revisions (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            message_id BIGINT UNSIGNED NOT NULL,
            editor_participant_id BIGINT UNSIGNED NOT NULL,
            previous_body MEDIUMTEXT NOT NULL,
            new_body MEDIUMTEXT NOT NULL,
            edited_at DATETIME NOT NULL,
            INDEX idx_message_revisions_message (message_id, edited_at),
            CONSTRAINT fk_message_revisions_message FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE,
            CONSTRAINT fk_message_revisions_editor FOREIGN KEY (editor_participant_id) REFERENCES project_participants(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS pinned_messages (
            project_id BIGINT UNSIGNED NOT NULL,
            message_id BIGINT UNSIGNED NOT NULL,
            pinned_by_participant_id BIGINT UNSIGNED NOT NULL,
            created_at DATETIME NOT NULL,
            PRIMARY KEY (project_id, message_id),
            CONSTRAINT fk_pinned_messages_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
            CONSTRAINT fk_pinned_messages_message FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE,
            CONSTRAINT fk_pinned_messages_participant FOREIGN KEY (pinned_by_participant_id) REFERENCES project_participants(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS agent_credential_scopes (
            agent_id BIGINT UNSIGNED NOT NULL,
            scope VARCHAR(80) NOT NULL,
            created_at DATETIME NOT NULL,
            PRIMARY KEY (agent_id, scope),
            CONSTRAINT fk_agent_credential_scopes_agent FOREIGN KEY (agent_id) REFERENCES chat_agents(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS system_settings (
            setting_key VARCHAR(120) PRIMARY KEY,
            value_json MEDIUMTEXT NULL,
            encrypted_value MEDIUMTEXT NULL,
            updated_by_user_id BIGINT UNSIGNED NULL,
            updated_at DATETIME NOT NULL,
            CONSTRAINT fk_system_settings_editor FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS administrative_audit_events (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            actor_user_id BIGINT UNSIGNED NULL,
            action VARCHAR(100) NOT NULL,
            subject_type VARCHAR(60) NULL,
            subject_id VARCHAR(120) NULL,
            metadata_json MEDIUMTEXT NULL,
            ip_address VARCHAR(80) NULL,
            created_at DATETIME NOT NULL,
            INDEX idx_administrative_audit_created (created_at, id),
            INDEX idx_administrative_audit_actor (actor_user_id, created_at),
            CONSTRAINT fk_administrative_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS message_events_outbox (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            event_uuid CHAR(36) NOT NULL UNIQUE,
            project_id BIGINT UNSIGNED NOT NULL,
            message_id BIGINT UNSIGNED NULL,
            event_type VARCHAR(100) NOT NULL,
            project_sequence BIGINT UNSIGNED NULL,
            payload_json MEDIUMTEXT NOT NULL,
            attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
            available_at DATETIME NOT NULL,
            published_at DATETIME NULL,
            failed_at DATETIME NULL,
            last_error VARCHAR(500) NULL,
            created_at DATETIME NOT NULL,
            INDEX idx_message_events_outbox_pending (published_at, failed_at, available_at, id),
            CONSTRAINT fk_message_events_outbox_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
            CONSTRAINT fk_message_events_outbox_message FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS security_rate_limits (
            bucket_key CHAR(64) PRIMARY KEY,
            action VARCHAR(60) NOT NULL,
            window_started_at DATETIME NOT NULL,
            hit_count INT UNSIGNED NOT NULL DEFAULT 0,
            blocked_until DATETIME NULL,
            updated_at DATETIME NOT NULL,
            INDEX idx_security_rate_limits_cleanup (updated_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ],
];
