<?php

return [
    'version' => '202609070003_chatgpt_oauth',
    'description' => 'Add project-agent OAuth grants for the ChatGPT MCP plugin',
    'statements' => [
        "CREATE TABLE IF NOT EXISTS oauth_clients (
            client_id VARCHAR(160) PRIMARY KEY,
            client_name VARCHAR(160) NOT NULL,
            redirect_uris_json TEXT NOT NULL,
            token_endpoint_auth_method VARCHAR(40) NOT NULL DEFAULT 'none',
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "ALTER TABLE oauth_clients MODIFY client_id VARCHAR(160) NOT NULL",
        "CREATE TABLE IF NOT EXISTS oauth_authorization_codes (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            code_hash CHAR(64) NOT NULL UNIQUE,
            client_id VARCHAR(160) NOT NULL,
            user_id BIGINT UNSIGNED NOT NULL,
            project_id BIGINT UNSIGNED NOT NULL,
            agent_id BIGINT UNSIGNED NOT NULL,
            redirect_uri VARCHAR(1024) NOT NULL,
            resource_uri VARCHAR(1024) NOT NULL,
            scope_text VARCHAR(1000) NOT NULL,
            code_challenge VARCHAR(128) NOT NULL,
            created_at DATETIME NOT NULL,
            expires_at DATETIME NOT NULL,
            consumed_at DATETIME NULL,
            INDEX idx_oauth_codes_expiry (expires_at, consumed_at),
            CONSTRAINT fk_oauth_codes_client FOREIGN KEY (client_id) REFERENCES oauth_clients(client_id) ON DELETE CASCADE,
            CONSTRAINT fk_oauth_codes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            CONSTRAINT fk_oauth_codes_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
            CONSTRAINT fk_oauth_codes_agent FOREIGN KEY (agent_id) REFERENCES chat_agents(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS oauth_access_tokens (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            token_hash CHAR(64) NOT NULL UNIQUE,
            client_id VARCHAR(160) NOT NULL,
            user_id BIGINT UNSIGNED NOT NULL,
            project_id BIGINT UNSIGNED NOT NULL,
            agent_id BIGINT UNSIGNED NOT NULL,
            resource_uri VARCHAR(1024) NOT NULL,
            scope_text VARCHAR(1000) NOT NULL,
            created_at DATETIME NOT NULL,
            expires_at DATETIME NOT NULL,
            last_used_at DATETIME NULL,
            revoked_at DATETIME NULL,
            INDEX idx_oauth_access_expiry (expires_at, revoked_at),
            CONSTRAINT fk_oauth_access_client FOREIGN KEY (client_id) REFERENCES oauth_clients(client_id) ON DELETE CASCADE,
            CONSTRAINT fk_oauth_access_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            CONSTRAINT fk_oauth_access_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
            CONSTRAINT fk_oauth_access_agent FOREIGN KEY (agent_id) REFERENCES chat_agents(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS oauth_refresh_tokens (
            id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
            token_hash CHAR(64) NOT NULL UNIQUE,
            access_token_id BIGINT UNSIGNED NOT NULL,
            client_id VARCHAR(160) NOT NULL,
            user_id BIGINT UNSIGNED NOT NULL,
            project_id BIGINT UNSIGNED NOT NULL,
            agent_id BIGINT UNSIGNED NOT NULL,
            resource_uri VARCHAR(1024) NOT NULL,
            scope_text VARCHAR(1000) NOT NULL,
            created_at DATETIME NOT NULL,
            expires_at DATETIME NOT NULL,
            consumed_at DATETIME NULL,
            revoked_at DATETIME NULL,
            INDEX idx_oauth_refresh_expiry (expires_at, consumed_at, revoked_at),
            CONSTRAINT fk_oauth_refresh_access FOREIGN KEY (access_token_id) REFERENCES oauth_access_tokens(id) ON DELETE CASCADE,
            CONSTRAINT fk_oauth_refresh_client FOREIGN KEY (client_id) REFERENCES oauth_clients(client_id) ON DELETE CASCADE,
            CONSTRAINT fk_oauth_refresh_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
            CONSTRAINT fk_oauth_refresh_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
            CONSTRAINT fk_oauth_refresh_agent FOREIGN KEY (agent_id) REFERENCES chat_agents(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ],
];
