<?php

return [
    'version' => '202609240002',
    'description' => 'Add project tasks and immutable task activity events',
    'statements' => [
        "CREATE TABLE IF NOT EXISTS project_tasks (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            public_id CHAR(36) NOT NULL,
            project_id BIGINT UNSIGNED NOT NULL,
            title VARCHAR(180) NOT NULL,
            description TEXT NULL,
            acceptance_criteria MEDIUMTEXT NULL,
            status ENUM('open','in_progress','in_review','blocked','completed','cancelled') NOT NULL DEFAULT 'open',
            priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
            assignee_participant_id BIGINT UNSIGNED NULL,
            supervising_participant_id BIGINT UNSIGNED NULL,
            created_by_participant_id BIGINT UNSIGNED NOT NULL,
            source_message_id BIGINT UNSIGNED NULL,
            due_at DATETIME NULL,
            blocked_reason TEXT NULL,
            completion_summary TEXT NULL,
            version BIGINT UNSIGNED NOT NULL DEFAULT 1,
            started_at DATETIME NULL,
            submitted_at DATETIME NULL,
            completed_at DATETIME NULL,
            cancelled_at DATETIME NULL,
            created_at DATETIME NOT NULL,
            updated_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            UNIQUE KEY uq_project_tasks_public_id (public_id),
            KEY idx_project_tasks_project_status (project_id, status, updated_at),
            KEY idx_project_tasks_assignee (project_id, assignee_participant_id, status),
            KEY idx_project_tasks_supervisor (project_id, supervising_participant_id, status),
            KEY idx_project_tasks_due (project_id, due_at),
            KEY idx_project_tasks_source (source_message_id),
            CONSTRAINT fk_project_tasks_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
            CONSTRAINT fk_project_tasks_assignee FOREIGN KEY (assignee_participant_id) REFERENCES project_participants(id) ON DELETE SET NULL,
            CONSTRAINT fk_project_tasks_supervisor FOREIGN KEY (supervising_participant_id) REFERENCES project_participants(id) ON DELETE SET NULL,
            CONSTRAINT fk_project_tasks_creator FOREIGN KEY (created_by_participant_id) REFERENCES project_participants(id),
            CONSTRAINT fk_project_tasks_source FOREIGN KEY (source_message_id) REFERENCES messages(id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS project_task_events (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
            task_id BIGINT UNSIGNED NOT NULL,
            project_id BIGINT UNSIGNED NOT NULL,
            actor_participant_id BIGINT UNSIGNED NOT NULL,
            event_type VARCHAR(40) NOT NULL,
            from_status VARCHAR(24) NULL,
            to_status VARCHAR(24) NULL,
            body TEXT NULL,
            metadata_json JSON NULL,
            created_at DATETIME NOT NULL,
            PRIMARY KEY (id),
            KEY idx_project_task_events_task (task_id, id),
            KEY idx_project_task_events_project (project_id, created_at, id),
            KEY idx_project_task_events_actor (actor_participant_id, created_at),
            CONSTRAINT fk_project_task_events_task FOREIGN KEY (task_id) REFERENCES project_tasks(id) ON DELETE CASCADE,
            CONSTRAINT fk_project_task_events_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
            CONSTRAINT fk_project_task_events_actor FOREIGN KEY (actor_participant_id) REFERENCES project_participants(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
    ],
];
